#!/bin/bash
# Economy Manager V1 - Interactive Setup Script
# Version: 1.0.0
# This script runs AFTER the repository has been cloned

set -e

# ────────────────────────────────────────────────
# Colors
# ────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Ensure we are running in an interactive terminal
if [ ! -t 0 ]; then
    echo -e "${RED}ERROR:${NC} This setup wizard requires an interactive terminal with user input."
    echo "Please run: ./setup-interactive.sh" >&2
    exit 1
fi

# ────────────────────────────────────────────────
# Welcome Message
# ────────────────────────────────────────────────
echo -e "${CYAN}╔══════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║      Interactive Configuration Wizard       ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════╝${NC}"
echo ""

# ────────────────────────────────────────────────
# Step 1: Install Python dependencies
# ────────────────────────────────────────────────
echo -e "${BLUE}[Step 1/4]${NC} Installing Python dependencies..."
echo ""

if pip3 install -r requirements.txt --user; then
  echo ""
  echo -e "${GREEN}  ✓ Dependencies installed successfully${NC}"
else
  echo ""
  echo -e "${RED}  ✗ Failed to install dependencies${NC}"
  exit 1
fi

# ────────────────────────────────────────────────
# Step 2: Interactive configuration
# ────────────────────────────────────────────────
echo ""
echo -e "${BLUE}[Step 2/4]${NC} Database Configuration"
echo -e "${CYAN}═══════════════════════════════════════════════${NC}"
echo ""

# Python interactive configuration
python3 << 'PYTHON_CONFIG'
import os
import sys
import mysql.connector
from mysql.connector import Error

def get_input(prompt, default=None, secret=False):
    """Get input with optional default value."""
    if default:
        value = input(f"{prompt} [{default}]: ").strip()
        return value or default
    else:
        value = input(f"{prompt}: ").strip()
        return value

def test_database(config):
    """Test database connection."""
    print("\n🔍 Testing database connection...")
    try:
        conn = mysql.connector.connect(
            host=config['db_host'],
            port=int(config['db_port']),
            user=config['db_user'],
            password=config['db_password'],
            database=config['db_name']
        )
        
        if conn.is_connected():
            print("✅ Database connection successful!")
            
            # Check for table
            cursor = conn.cursor()
            cursor.execute(f"SHOW TABLES LIKE '{config['table_name']}'")
            
            if cursor.fetchone():
                print(f"✅ Table '{config['table_name']}' found")
            else:
                print(f"⚠️  Table '{config['table_name']}' not found")
                print("\nExpected table structure:")
                print("  - name (MEDIUMTEXT)")
                print("  - uuid (MEDIUMTEXT)")
                print("  - gems (DOUBLE)")
                print("  - coins (DOUBLE)")
                
            cursor.close()
            conn.close()
            return True
            
    except Error as e:
        print(f"❌ Connection failed: {e}")
        return False

def write_env_file(config):
    """Write configuration to .env file."""
    try:
        with open(".env", "w") as f:
            f.write("# Economy Manager Configuration\n")
            f.write("# Generated by setup wizard\n\n")
            
            f.write("# Database Configuration\n")
            f.write(f"DB_HOST={config['db_host']}\n")
            f.write(f"DB_PORT={config['db_port']}\n")
            f.write(f"DB_USER={config['db_user']}\n")
            f.write(f"DB_PASSWORD={config['db_password']}\n")
            f.write(f"DB_NAME={config['db_name']}\n\n")
            
            f.write("# Discord Configuration\n")
            f.write(f"DISCORD_TOKEN={config['discord_token']}\n")
            if config.get('guild_id'):
                f.write(f"GUILD_ID={config['guild_id']}\n")
            f.write("\n")
            
            f.write("# Optional Configuration\n")
            f.write(f"TABLE_NAME={config['table_name']}\n")
            if config.get('admin_role_id'):
                f.write(f"ADMIN_ROLE_ID={config['admin_role_id']}\n")
            if config.get('log_channel_id'):
                f.write(f"LOG_CHANNEL_ID={config['log_channel_id']}\n")
            f.write("\n")
            
            f.write("# Logging\n")
            f.write("LOG_LEVEL=INFO\n")
            f.write("LOG_FILE=logs/bot.log\n")
            
        print("\n✅ Configuration saved to .env")
        return True
        
    except Exception as e:
        print(f"\n❌ Failed to write .env file: {e}")
        return False

def main():
    config = {}
    
    # Database configuration
    print("📊 Database Settings")
    print("-" * 50)
    config['db_host'] = get_input("Database Host", "localhost")
    config['db_port'] = get_input("Database Port", "3306")
    config['db_user'] = get_input("Database Username")
    config['db_password'] = get_input("Database Password", secret=True)
    config['db_name'] = get_input("Database Name", "coinsengine_shared")
    config['table_name'] = get_input("Table Name", "coinsengine_users")
    
    # Test database connection
    if not test_database(config):
        retry = input("\n⚠️  Database test failed. Continue anyway? (y/N): ").strip().lower()
        if retry != 'y':
            print("❌ Setup cancelled")
            sys.exit(1)
    
    # Discord configuration
    print("\n🤖 Discord Settings")
    print("-" * 50)
    config['discord_token'] = get_input("Discord Bot Token")
    config['guild_id'] = get_input("Guild ID (Server ID)", "").strip()
    
    # Optional configuration
    print("\n⚙️  Optional Settings")
    print("-" * 50)
    config['admin_role_id'] = get_input("Admin Role ID (leave empty to skip)", "").strip()
    config['log_channel_id'] = get_input("Log Channel ID (leave empty to skip)", "").strip()
    
    # Write configuration
    if write_env_file(config):
        print("\n" + "="*50)
        print("✅ Configuration complete!")
        print("="*50)
    else:
        sys.exit(1)

if __name__ == "__main__":
    main()
PYTHON_CONFIG

if [ $? -ne 0 ]; then
  echo ""
  echo -e "${RED}Configuration failed. Please run this script again.${NC}"
  exit 1
fi

# ────────────────────────────────────────────────
# Step 3: Create logs directory
# ────────────────────────────────────────────────
echo ""
echo -e "${BLUE}[Step 3/4]${NC} Setting up directories..."

mkdir -p logs
echo -e "${GREEN}  ✓ Logs directory created${NC}"

# ────────────────────────────────────────────────
# Step 4: Final instructions
# ────────────────────────────────────────────────
echo ""
echo -e "${BLUE}[Step 4/4]${NC} Ready to start!"
echo ""
echo -e "${CYAN}═══════════════════════════════════════════════${NC}"
echo -e "${GREEN}Configuration complete!${NC}"
echo -e "${CYAN}═══════════════════════════════════════════════${NC}"
echo ""
echo "To start the bot:"
echo -e "  ${YELLOW}python3 bot/main.py${NC}"
echo ""
echo "To run in background:"
echo -e "  ${YELLOW}nohup python3 bot/main.py > logs/bot.log 2>&1 &${NC}"
echo ""
echo "To view logs:"
echo -e "  ${YELLOW}tail -f logs/bot.log${NC}"
echo ""

# Ask to start bot
read -p "Do you want to start the bot now? (Y/n): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Nn]$ ]]; then
  echo ""
  echo -e "${GREEN}Starting Economy Manager Bot...${NC}"
  echo ""
  python3 bot/main.py
fi
