"""
Setup Script for Economy Manager V1
Version: 0.1.0
Interactive configuration for the bot
"""

import os
import sys
import mysql.connector
from mysql.connector import Error

def print_header():
    """Print setup header."""
    print("=" * 50)
    print("Economy Manager V1 - Setup")
    print("=" * 50)
    print()

def get_input(prompt: str, default: str = None) -> str:
    """Get input from user with optional default."""
    if default:
        user_input = input(f"{prompt} [{default}]: ").strip()
        return user_input if user_input else default
    return input(f"{prompt}: ").strip()

def test_database_connection(host: str, port: int, user: str, password: str, database: str) -> bool:
    """
    Test database connection.
    
    Returns:
        True if successful, False otherwise
    """
    try:
        print("\n🔍 Testing database connection...")
        connection = mysql.connector.connect(
            host=host,
            port=port,
            user=user,
            password=password,
            database=database
        )
        
        if connection.is_connected():
            print("✅ Database connection successful!")
            
            # Check if players table exists
            cursor = connection.cursor()
            cursor.execute("SHOW TABLES LIKE 'players'")
            result = cursor.fetchone()
            
            if result:
                print("✅ 'players' table found")
            else:
                print("⚠️  'players' table not found. Please create it before running the bot.")
                print("\nExample SQL:")
                print("""
CREATE TABLE players (
    id INT AUTO_INCREMENT PRIMARY KEY,
    player_name VARCHAR(255) NOT NULL,
    uuid VARCHAR(36),
    gems INT DEFAULT 0,
    coins INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
""")
            
            cursor.close()
            connection.close()
            return True
        else:
            print("❌ Failed to connect to database")
            return False
            
    except Error as e:
        print(f"❌ Database connection error: {e}")
        return False

def create_env_file(config: dict):
    """Create .env file with configuration."""
    env_path = '.env'
    
    try:
        with open(env_path, 'w') as f:
            f.write("# Economy Manager V1 Configuration\n")
            f.write("# Generated by setup script\n\n")
            
            f.write("# Database Configuration\n")
            f.write(f"DB_HOST={config['db_host']}\n")
            f.write(f"DB_PORT={config['db_port']}\n")
            f.write(f"DB_USER={config['db_user']}\n")
            f.write(f"DB_PASSWORD={config['db_password']}\n")
            f.write(f"DB_NAME={config['db_name']}\n\n")
            
            f.write("# Discord Configuration\n")
            f.write(f"DISCORD_TOKEN={config['discord_token']}\n")
            f.write(f"GUILD_ID={config['guild_id']}\n\n")
            
            f.write("# Optional Configuration\n")
            f.write(f"TABLE_NAME={config.get('table_name', 'players')}\n")
            if config.get('admin_role_id'):
                f.write(f"ADMIN_ROLE_ID={config['admin_role_id']}\n")
            f.write("\n# Logging\n")
            f.write("LOG_LEVEL=INFO\n")
            f.write("LOG_FILE=logs/bot.log\n")
            
        print(f"\n✅ Configuration saved to {env_path}")
        return True
        
    except Exception as e:
        print(f"\n❌ Error creating .env file: {e}")
        return False

def main():
    """Main setup function."""
    print_header()
    
    config = {}
    
    # Database configuration
    print("📊 Database Configuration")
    print("-" * 50)
    config['db_host'] = get_input("Database Host", "localhost")
    config['db_port'] = get_input("Database Port", "3306")
    config['db_user'] = get_input("Database User")
    config['db_password'] = get_input("Database Password")
    config['db_name'] = get_input("Database Name", "minecraft_economy")
    config['table_name'] = get_input("Players Table Name", "players")
    
    # Test database connection
    if not test_database_connection(
        host=config['db_host'],
        port=int(config['db_port']),
        user=config['db_user'],
        password=config['db_password'],
        database=config['db_name']
    ):
        print("\n❌ Setup failed due to database connection error.")
        print("Please check your database credentials and try again.")
        sys.exit(1)
    
    # Discord configuration
    print("\n🤖 Discord Configuration")
    print("-" * 50)
    config['discord_token'] = get_input("Discord Bot Token")
    config['guild_id'] = get_input("Server/Guild ID (optional)", "")
    config['admin_role_id'] = get_input("Admin Role ID (optional)", "")
    
    # Create .env file
    if create_env_file(config):
        print("\n" + "=" * 50)
        print("✅ Setup Complete!")
        print("=" * 50)
        print("\nYou can now start the bot with:")
        print("  python bot/main.py")
        print("\nOr on Windows:")
        print("  python bot\\main.py")
        print()
    else:
        print("\n❌ Setup failed. Please try again.")
        sys.exit(1)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Unexpected error: {e}")
        sys.exit(1)
